apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: greeting-api
  description: "Greets callers, stores each greeting and publishes a greeting event"
  annotations:
    github.com/project-slug: wasp-foundry/greeting-api
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: greeting-api
spec:
  type: service
  lifecycle: experimental
  system: greeter
  owner: "group:default/team-alpha"
  dependsOn:
    - resource:default/development
    - resource:default/production
